name: CI

on:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  validate:

    uses: ./.github/workflows/flutter-validate.yml
  
  release:

    needs: validate

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build Android APK (debug)
        run: flutter build apk --debug